name = "nanolux"
uuid = "9e1bbf0d-3400-4a76-8ebd-2a15219acd99"
version = "0.1.0"
authors = ["Ralph Kube <ralph_kube@gmx.net>"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ADTypes = "1.18.0"
BenchmarkTools = "1.6.3"
Distributions = "0.25.122"
Enzyme = "0.13.87"
GLMakie = "0.13.6"
Lux = "1.24.0"
OneHotArrays = "0.2.10"
Optimisers = "0.4.6"
Zygote = "0.7.10"
