[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NanoLux = "9e1bbf0d-3400-4a76-8ebd-2a15219acd99"
